#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := face_recognition_command_line

SOLUTION_PATH ?= $(abspath $(shell pwd))/../../..

EXTRA_COMPONENT_DIRS = $(IDF_PATH)/examples/common_components/protocol_examples_common


include $(SOLUTION_PATH)/components/component_conf.mk
include $(IDF_PATH)/make/project.mk
